# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d55223509779a50e4e0ea58b977da328a24c27010ee56c3e3bdc131d2f46495829e88939a1478c2248b1315e24487d787efa8f6255683b1022ae406e5661482d

test:
  secret_key_base: e74483cd02ad1f4656d2746e03856a877e7e8b934ce6743632b06f5112553301e07b58ec11c1f7269ca1ac3d81165256988304cea53746546b4d1819d92ba9de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
